apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ioq3-dedicated.fullname" . }}-config
  labels:
    {{- include "ioq3-dedicated.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.ioq3Configs }}
  {{ $key }}: |
    {{- $value | nindent 4 }}
  {{- end }}