apiVersion: v1
kind: Service
metadata:
  name: {{ include "ioq3-dedicated.fullname" . }}
  labels:
    {{- include "ioq3-dedicated.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: quake
      protocol: UDP
      name: quake
  selector:
    {{- include "ioq3-dedicated.selectorLabels" . | nindent 4 }}
